services:
  - type: web
    name: employee-payroll-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn employee_payroll_system.wsgi --log-file -"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "your-secret-key"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "employee-payroll-app.onrender.com"
      - key: DB_NAME
        fromDatabase:
          name: employee-payroll-db
          property: name
      - key: DB_USER
        fromDatabase:
          name: employee-payroll-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: employee-payroll-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: employee-payroll-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: employee-payroll-db
          property: port
