# Generated by Django 5.2.7 on 2025-10-07 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True, verbose_name='Employee ID')),
                ('department', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Basic Salary')),
                ('hra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='H.R.A')),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Other Allowance')),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='P.F. Deduction')),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax Deduction')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('hire_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
